baseurl = "http://www.johnbot.me/"
languageCode = "en-us"
title = "Web Portfolio of John Westhoff"
[params]
    github = "http://github.com/johnathonnow"
    linkedin = "https://www.linkedin.com/in/johnjwesthoff"
    name = "John Westhoff"
    bio = "I am currently a sophomore Computer Science student at the University of Notre Dame. I am interested in Robotics, and I help coach a local South Bend team. I am a member of the Notre Dame Linux Users Group. I enjoy working on side projects, some of which I intend to post here."
