baseurl = "https://www.johnbot.me"
languageCode = "en-us"
title = "Web Portfolio of John Westhoff"
[params]
    github = "http://github.com/johnathonnow"
    linkedin = "https://www.linkedin.com/in/johnjwesthoff"
    name = "John Westhoff"
    avatar = "../../img/avatar.jpg"
    bio = "I am currently a rising Junior Computer Science student at the University of Notre Dame. I am interested in Robotics, and I help coach a local South Bend team. I am a member of the Notre Dame Linux Users Group, which affectionately calls me Jeffrey. I enjoy working on side projects, some of which I intend to post here.."
[taxonomies]
tag = "tags"
category = "categories"
series = "series"
