baseurl = "https://johnwesthoff.com"
languageCode = "en-us"
title = "Project Blog of John Westhoff"
[params]
    github = "http://github.com/johnathonnow"
    linkedin = "https://www.linkedin.com/in/johnjwesthoff"
    name = "John Westhoff"
    avatar = "../../img/avatar.jpg"
    visible = ""
[taxonomies]
tag = "tags"
category = "categories"
series = "series"
