baseurl = "https://www.johnbot.me"
languageCode = "en-us"
title = "Project Block of John Westhoff"
[params]
    github = "http://github.com/johnathonnow"
    linkedin = "https://www.linkedin.com/in/johnjwesthoff"
    name = "John Westhoff"
    avatar = "../../img/avatar.jpg"
    bio = "See [my about page](https://www.johnbot.me/about)."
    visible = ""
[taxonomies]
tag = "tags"
category = "categories"
series = "series"
