baseurl = "https://johnwesthoff.com"
languageCode = "en-us"
title = "John Westhoff's Blog"
[params]
    github = "http://github.com/johnathonnow"
    linkedin = "https://www.linkedin.com/in/johnjwesthoff"
    name = "John Westhoff"
    avatar = "../../img/avatar.jpg"
    visible = ""
    heading = "Projects"
[taxonomies]
tag = "tags"
category = "categories"
series = "series"
